### ISSUE TITLE
As a developer, I want to be able to integrate the Google Maps JavaScript API into the app so that we can use it for the maps feature

### ISSUE THREAD

**Issue by Hgersten-hash** [gcivil-nyu-org/INET-Monday-Spring2023-Team-2#114]
**User story**
As a developer, I want to be able to integrate the Google Maps JavaScript API into the app so that we can use it for the maps feature

**Acceptance criteria**
1. The Google Maps JavaScript API key should be securely stored and not visible in any client-side code or repository.
2. The API key should be valid and authorized to access the required APIs (e.g., Maps JavaScript API, Places API, Geocoding API).
3. The API should be properly configured with any required billing information, usage limits, or usage restrictions.
**Definition of Done**
I know this story is complete when we have successfully integrated Google Maps API in our app with the appropriate configurations

**Comment by joeleu** [comment]
Here is the configuration for each of the keys. I've limited the allowed APIs to just the `Maps JavaScript API` since it is the broadest, if we end up needing access to the other APIs we can add them.

![Screenshot 2023-03-22 at 21 36 30](https://user-images.githubusercontent.com/15133747/227076558-ef2ed658-21e4-415d-9a55-2d1e7e084f9b.png)

![Screenshot 2023-03-22 at 21 37 13](https://user-images.githubusercontent.com/15133747/227076641-f9c6d921-7bac-46a4-b805-4f80f7a82eef.png)
